# Generated by Django 4.2.6 on 2023-11-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0004_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carconfigurationorder",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
