# Generated by Django 4.2.6 on 2023-11-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0005_alter_carconfigurationorder_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="carconfigurationorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
